[package]
name = "rust-riemann_health"
version = "0.1.0"
authors = ["Raj Kiran Gade <rajkiran.gade@gmail.com>"]

[dependencies]
sys-info = "0.5.4"
riemann_client = { path = "../rust-riemann_client"}
protobuf = "1.4.3"